spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.resources.static-locations: classpath:/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: websocket
server:
  port: 8785
#logging:
#  level:
#    root: debug